apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rafood-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "rafood-api.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "rafood-api.name" . }}

    spec:
      containers:
        - name: rafood-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}
