{
 "title": "Rafood Database Metrics",
 "description": "All basic Rafood Database (Postgres) metrics.",
 "tags": [
  "database",
  "postgres"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Connections ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Usage Percentage ",
     "type": "gauge",
     "description": "Percentage of used connections relative to the configured maximum.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{state=\"active\"}) / sum(pg_settings_max_connections) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "gauge",
     "description": "Number of active client connections to the database.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{state=\"active\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Idle Connections",
     "type": "gauge",
     "description": "Queries with opened pools but without use.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{state=\"idle\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Idle in Transaction Connections",
     "type": "gauge",
     "description": "Connections with transaction still opened or somehow stuck.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{state=\"idle in transaction\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  }
 ]
}