apiVersion: v1
kind: Service
metadata:
  name: rafood-api-service
  labels:
    app: rafood-api
spec:
  selector:
    app: rafood-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8000
      nodePort: 31110
