name: Setup Poetry and Install Dependencies
description: Instala o Poetry e as dependências do projeto
inputs:
  python-version:
    description: Versão do Python
    required: true
  poetry-extras:
    description: "Extras do poetry (ex: \"--with dev\")"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      shell: bash
      run: |
        pip install poetry==2.1.4
        poetry config virtualenvs.create false

    - name: Enable Poetry cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          ~/.cache/pip
        key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      shell: bash
      run: poetry install --no-interaction --no-ansi --no-root ${{ inputs.poetry-extras }}